#! /bin/bash
#usage
#provide an IPsource / list of IPs
#provide a password to test with a null user
#Exampel ./Auto_curl.sh <Ipsource/$1> <password/$2>

### Future version will allow a user and password parameter

for i in $(cat $1); do
    echo "###$i###" >> $1.ac_out.txt
    query="$(curl --max-time 5.5 -u '':$2 $i)"
    echo "$query" >> $1.ac_out.txt
done

#to do - If Curl receives a 404/ 401 / nothing omit or filter on
# how should I format IP addresses to make them easier to collect with awk or similar utility
